# we are extending everything from tomcat:8.0 image ...
FROM tomcat:latest
MAINTAINER pedrosantos
# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat
COPY target/maven-archetype-webapp.war /usr/local/tomcat/apache-tomcat-9.0.39/webapps/
